### ISSUE TITLE
Research .ics format and Moodle calendar export

### ISSUE THREAD

**Issue by dantetemplar** [one-zero-eight/InNoHassle-Events#43]
https://moodle.innopolis.university/calendar/export.php?

- [x] suggest ideas about "quiz opens" and "quiz closes"
- [x] suggest ideas about "lab due"
- [x] write code snippet to parse moodle calendar from url (without auth)

**Comment by dantetemplar** [comment]
@dantetemplar test comment

**Comment by peplxx** [comment]
## Deadline events
If event name contains "is due", hence it will be considered as deadline event (duration of this will be from 00:00 this date to 00:00 next date)
how it will look like in calendar:


![Image](https://github.com/one-zero-eight/InNoHassle-Events/assets/91543105/01e5559e-5f48-4a7a-8a8d-693ae453ef06)



Because not all deadlines are to 23:59 PM hence i added to description comment: Due to: {time of deadline


![Image](https://github.com/one-zero-eight/InNoHassle-Events/assets/91543105/76887a4f-33c2-4e2c-a5c6-752b48556adf)

## Quizes
If event contains "opens" or "closes" it will be collected in array
After all events is proceeded this events will be sorted by id (open events has lower id when closes)
 

![Image](https://github.com/one-zero-eight/InNoHassle-Events/assets/91543105/d4fa3698-cec2-4c06-a24e-34fe299155db)


After that we can easy merge pairs of them into independent events:


![Image](https://github.com/one-zero-eight/InNoHassle-Events/assets/91543105/385c2414-d9f7-49c2-a4a1-5dd9bcc56c27)



## Extra course info which can be parsed form calendar
And also in categories we can get course which event is conducted for
We can just add this course to description for every event in calnedar


![Image](https://github.com/one-zero-eight/InNoHassle-Events/assets/91543105/b2c9f86e-032d-4285-869b-a7fc303ab9e4)

 

![Image](https://github.com/one-zero-eight/InNoHassle-Events/assets/91543105/80670576-620b-4b54-a561-7ec3fed61a27)

**Comment by peplxx** [comment]
```
import datetime

from ics import Calendar, Todo, Event
from datetime import timedelta, datetime
import requests

MSK_TIMEZONE = timedelta(hours=3)


def fix_courses_names(courses: set) -> set:
    fixed = set()
    for course in courses:
        prefix, course_name = course.split(']')
        prefix += ']'
        fixed |= {f'{prefix} {course_name}'}
    return fixed


def make_deadline(event: Event, timezone_delta: timedelta) -> Event:
    item = event
    item.description = f"Due to: {str((event.end + timezone_delta).time())[:-3]}\n"
    date = item.begin.date()
    item.name = "[DEADLINE] " + item.name
    item.begin = datetime(day=date.day, year=date.year, month=date.month) - timezone_delta
    item.end = item.begin + timedelta(days=1)
    return item


def merge_events(opens: Event, closes: Event, timezone_delta: timedelta) -> Event:
    item = opens
    item.name = "[QUIZ] " + item.name.split('opens')[0]
    item.begin -= timezone_delta
    item.end = closes.end - timezone_delta
    return item


def process(*, calendar_url: str = None,
            file_path: str = None,
            output: str = "fixed.ics") -> None:
    from_url = True if calendar_url else False
    if from_url:
        responce = requests.get(calendar_url)
        responce.encoding = responce.apparent_encoding
        c = Calendar(responce.text)
    else:
        c = Calendar(open(file_path, 'r', encoding='utf-8').read())

    new_calendar = Calendar()

    open_close_events = []

    for event in c.events:
        print("Processing event:", event.name)
        if event.duration == timedelta(0):
            if "closes" in event.name or 'opens' in event.name:
                open_close_events.append(event)
            else:
                new_calendar.events.add(make_deadline(event, MSK_TIMEZONE))
        else:
            new_calendar.events.add(event)
    open_close_events = sorted(open_close_events, key=lambda x: int(x.uid.split('@')[0]))
    print([(i.name,i.uid) for i in open_close_events])
    for i, opens in enumerate(open_close_events[::2]):
        if 'opens' not in opens.name:
            print(f"Not open event {opens.name}!")
            continue
        try:
            close_event = open_close_events[i + 1]
            new_calendar.events.add(merge_events(opens, close_event, MSK_TIMEZONE))
        except IndexError as e:
            print(f"No close event for {opens.name}!")

    for e in new_calendar.events:
        e.description += f'Course: {"".join(fix_courses_names(e.categories))}\n'
    with open(f'{output}', 'w', encoding='utf-8') as f:
        f.writelines(new_calendar.serialize_iter())
    print("Done!")


if __name__ == "__main__":
    url = "https://moodle.innopolis.university/calendar/export_execute.php?userid=4281&authtoken=de421ca18a72b3d3284e31ce43c88aff5ed8c5ef&preset_what=all&preset_time=custom"
    process(calendar_url=url, output='my_calendar.ics')
``
```
